IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FactFlight')
    BEGIN
    DROP TABLE FactFlight
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DimPassenger')
    BEGIN
    DROP TABLE DimPassenger
    END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DimFlightDeparture')
    BEGIN
    DROP TABLE DimFlightDeparture
    END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DimFlightArrival')
    BEGIN
    DROP TABLE DimFlightArrival
END;


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DimDepartureTime')
    BEGIN
    DROP TABLE DimDepartureTime
END;


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DimPilot')
    BEGIN
    DROP TABLE DimPilot
        END;


